# Generated by Django 5.1.5 on 2025-02-08 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dispositivo'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='prioridade',
            field=models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta'), (4, 'Urgente')]),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(max_length=255),
        ),
    ]
