services:
  djangoapp:
    container_name: solarbanyu_back
    build:
      context: .
      dockerfile: Dockerfile  # Dockerfile do backend
    ports:
      - 8000:8000
    volumes:
      - ./solarbanyu_app:/solarbanyu_app
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./.env
    depends_on:
      - psql
    networks:
      - app-network

  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - app-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    env_file:
      - ./.env
    ports:
      - 8080:80
    user: '$UID:$GID'
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - app-network
    depends_on:
      - psql

  mqtta:
    container_name: mqtta
    build:
      context: ../embarcado  # Caminho para o diretório do mqttapp
      dockerfile: Dockerfile  # Dockerfile do mqttapp
    command: [ "sh", "scripts/start.sh" ]
    ports:
      - 5000:5000
    volumes:
      - ../embarcado:/app  # Ajustando o volume para o mqttapp
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    external: true
